### ISSUE TITLE
Error in backend product edit form

### ISSUE THREAD

**Issue by vmulot** [richardhj/contao-isotope_simple_stockmanagement#1]
Hi, i installed your ext, i activated it for a product type, and then i went in a product (in backend) to edit the stock.

when i closed the modal box, i had this error :
```
Warning: DOMDocument::loadHTML(): htmlParseEntityRef: expecting ';' in Entity, line: 21 in system/modules/isotope_simple_stockmanagement/src/Isotope/SimpleStockmanagement/Dca.php on line 77
#0 [internal function]: __error(2, 'DOMDocument::lo...', '/Applications/M...', 77, Array)
#1 system/modules/isotope_simple_stockmanagement/src/Isotope/SimpleStockmanagement/Dca.php(77): DOMDocument->loadHTML('

generateWizardList(Object(Contao\Database\Mysqli\Result), 'stock', Object(DcaWizard))
#3 system/modules/dcawizard/classes/DcaWizardHelper.php(90): DcaWizard->generate()
#4 system/modules/core/classes/Ajax.php(429): DcaWizardHelper->handleAjaxActions('reloadDcaWizard', Object(DC_ProductData))
#5 system/modules/core/classes/Ajax.php(411): Contao\Ajax->executePostActionsHook(Object(DC_ProductData))
#6 system/modules/core/classes/Backend.php(414): Contao\Ajax->executePostActions(Object(DC_ProductData))
#7 system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('iso_products')
#8 contao/main.php(20): Contao\BackendMain->run()
#9 {main}

```
any idea why ? (it seems  that the stock has a 0 for product_collection_id in tl_iso_stock)

thanks

**Comment by richardhj** [comment]
Hey, it is "just" a warning that does not influence the functionality.
It was a little bug in the extension dcawizard (terminal42/contao-dcawizard#17). Please have a look that you have installed dcawizard at v2.3.4.
