### ISSUE TITLE
Fatal error: The table name must not be empty

### ISSUE THREAD

**Issue by akroii** [richardhj/contao-isotope_simple_stockmanagement#13]
Wenn ich den Lagerbestand in einem Produkt hinzubuchen möchte, erhalte ich einen Fatal Error.

Schritte wie ich vorgegangen bin:
Installation -> Lagerbestand (stock) zu den Produkttypen hinzufügen (checkbox aktivieren) -> im Produkt einen Lagerstand hinzufügen -> Reload der Seite des Produktes im Backend -> "Ein Fehler ist aufgetreten"

Habe ich evtl. etwas übersehen?

Stacktrace:
```
[02-Apr-2018 12:49:03 Europe/Berlin] PHP Fatal error: Uncaught exception 'Exception' with message 'The table name must not be empty' thrown in /Applications/MAMP/htdocs/isotope/system/modules/core/library/Contao/DcaLoader.php on line 48
#0 /Applications/MAMP/htdocs/isotope/system/modules/core/library/Contao/Controller.php(1318): Contao\DcaLoader->__construct(NULL)
#1 /Applications/MAMP/htdocs/isotope/composer/vendor/codefog/contao-haste/library/Haste/Util/Format.php(69): Contao\Controller::loadDataContainer(NULL)
#2 /Applications/MAMP/htdocs/isotope/system/modules/dcawizard/templates/be_widget_dcawizard.html5(10): Haste\Util\Format::dcaLabel(NULL, 'quantity')
#3 /Applications/MAMP/htdocs/isotope/system/modules/core/library/Contao/BaseTemplate.php(88): include('/Applications/M...')
#4 /Applications/MAMP/htdocs/isotope/system/modules/core/library/Contao/Template.php(277): Contao\BaseTemplate->parse()
#5 /Applications/MAMP/htdocs/isotope/system/modules/core/classes/BackendTemplate.php(34): Contao\Template->parse()
#6 /Applications/MAMP/htdocs/isotope/composer/vendor/richardhj/contao-isotope_simple_stockmanagement/system/modules/isotope_simple_stockmanagement/src/Isotope/SimpleStockmanagement/Dca.php(77): Contao\BackendTemplate->parse()
#7 /Applications/MAMP/htdocs/isotope/composer/vendor/terminal42/dcawizard/widgets/DcaWizard.php(178): Isotope\SimpleStockmanagement\Dca->generateWizardList(Object(Contao\Database\Mysqli\Result), 'stock', Object(DcaWizard))
#8 /Applications/MAMP/htdocs/isotope/system/modules/core/library/Contao/Widget.php(684): DcaWizard->generate()
#9 /Applications/MAMP/htdocs/isotope/system/modules/core/templates/backend/be_widget.html5(3): Contao\Widget->generateWithError(true)
#10 /Applications/MAMP/htdocs/isotope/system/modules/core/library/Contao/BaseTemplate.php(88): include('/Applications/M...')
#11 /Applications/MAMP/htdocs/isotope/system/modules/core/library/Contao/Widget.php(630): Contao\BaseTemplate->parse()
#12 /Applications/MAMP/htdocs/isotope/system/modules/core/classes/DataContainer.php(557): Contao\Widget->parse()
#13 /Applications/MAMP/htdocs/isotope/composer/vendor/isotope/isotope-core/system/modules/isotope/drivers/DC_ProductData.php(598): Contao\DataContainer->row('{general_legend...')
#14 /Applications/MAMP/htdocs/isotope/system/modules/core/classes/Backend.php(650): DC_ProductData->edit()
#15 /Applications/MAMP/htdocs/isotope/system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('iso_products')
#16 /Applications/MAMP/htdocs/isotope/contao/main.php(20): Contao\BackendMain->run()
#17 {main}
```

PHP Version: 7.1.8
Contao: 3.5.28
contao-isotope_simple_stockmanagement: 1.0.2

**Comment by richardhj** [comment]
Duplicate of #9.
