### ISSUE TITLE
Backend error on product editing

### ISSUE THREAD

**Issue by GMTeams** [richardhj/contao-isotope_simple_stockmanagement#9]
Contao 3.5.33
Isotope dev-develop
contao-isotope_simple_stockmanagement 1.0.2
PHP 7

(It's Isotope dev-develop because we've implemented a new payment module, but it should be nearly the same as 2.4.5)

On product type I've added the attribute "stock" and activated "Lagerverwaltung aktivieren".

When I'm adding on the product settings a number in "Lagerbestand", the following error message is shown:

```
Fatal error: Uncaught exception Exception with message The table name must not be empty thrown in system/modules/core/library/Contao/DcaLoader.php on line 48
#0 system/modules/core/library/Contao/Controller.php(1318): Contao\DcaLoader->__construct(NULL)
#1 composer/vendor/codefog/contao-haste/library/Haste/Util/Format.php(69): Contao\Controller::loadDataContainer(NULL)
#2 system/modules/dcawizard/templates/be_widget_dcawizard.html5(10): Haste\Util\Format::dcaLabel(NULL, 'quantity')
#3 system/modules/core/library/Contao/BaseTemplate.php(88): include('/kunden/411850_...')
#4 system/modules/core/library/Contao/Template.php(277): Contao\BaseTemplate->parse()
#5 system/modules/core/classes/BackendTemplate.php(34): Contao\Template->parse()
#6 composer/vendor/richardhj/contao-isotope_simple_stockmanagement/system/modules/isotope_simple_stockmanagement/src/Isotope/SimpleStockmanagement/Dca.php(77): Contao\BackendTemplate->parse()
#7 composer/vendor/terminal42/dcawizard/widgets/DcaWizard.php(178): Isotope\SimpleStockmanagement\Dca->generateWizardList(Object(Contao\Database\Mysqli\Result), 'stock', Object(DcaWizard))
#8 system/modules/dcawizard/classes/DcaWizardHelper.php(110): DcaWizard->generate()
#9 system/modules/core/classes/Ajax.php(468): DcaWizardHelper->handleAjaxActions('reloadDcaWizard', Object(DC_ProductData))
#10 system/modules/core/classes/Ajax.php(450): Contao\Ajax->executePostActionsHook(Object(DC_ProductData))
#11 system/modules/core/classes/Backend.php(414): Contao\Ajax->executePostActions(Object(DC_ProductData))
#12 system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('iso_products')
#13 contao/main.php(20): Contao\BackendMain->run()
#14 {main}
```

Maybe it occurs because of wrong configuration, would be nice if you can help me.
Thanks.

**Comment by richardhj** [comment]
See #5.
Please install 2.0.x-dev
